### ISSUE TITLE
Unable to use the library with CMake

### ISSUE THREAD

**Issue by Tachi107** [dmitigr/pgfe#5]
Hi, I've trying to use `pgfe` as an header only library with CMake, but when building the makefiles with CMake I get these errors:
```
Dmitigr Cefeika header-only mode is set.
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find PostgreSQL (missing: PostgreSQL_TYPE_INCLUDE_DIR) (found
  version "13.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.18/Modules/FindPostgreSQL.cmake:247 (find_package_handle_standard_args)
  vendor/pgfe/lib/dmitigr/pgfe/CMakeLists.txt:358 (find_package)
```
I'm trying to compile my project on Debian Testing, and I've installed on my system `libpq-dev` and `postgresql-server-dev-all` version 13

**Comment by dmitigr** [comment]
Hey,

It's the problem of FindPostgreSQL bundled module of CMake. It seems that PostgreSQL 13 is too recent for CMake 3.18. You could either try:
  - to use most recent CMake;
  - to set the workaround variable `PostgreSQL_ADDITIONAL_VERSIONS` which is known by FindPostgreSQL module just before adding Pgfe, for example:
    ```cmake
      set(PostgreSQL_ADDITIONAL_VERSIONS "13")
      set(DMITIGR_CEFEIKA_HEADER_ONLY ON CACHE BOOL "Header-only?")
      add_subdirectory(third-party/pgfe)
    ```

Thanks for using Pgfe!

**Comment by Tachi107** [comment]
Thanks, this fixed the issue! Nice library by the way, keep it up!
