### ISSUE TITLE
How to retrieve data from a database / Documentation

### ISSUE THREAD

**Issue by Tachi107** [dmitigr/pgfe#8]
Let's say I have to save in a `std::string` the value of the field `name` of the record with and `id` equal to `3` in the table `users`, how can I do this with Pgfe?
The documentation clearly states how to perform queries to the database, but it's not so clear when it comes to retrieving data. I'm opening this also because the documentation in general seems to be based upon version 1 of Pgfe.

**Comment by dmitigr** [comment]
Thank you for opening this. The documentation needs to be improved and updated indeed.

**Comment by dmitigr** [comment]
I've reworked the documentation. Hope it's more clear now. The example 11 demonstrates exactly what you're looked for.

**Comment by Tachi107** [comment]
Woah, thanks, the documentation now is much better! 
I'll now start using Pgfe in a project of mine, I'll do my best to find (and maybe even fix) issues :)
